import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Calendar,
  GripVertical,
  PanelLeft,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  Ellipsis,
  Info,
  LoaderCircle,
  Lock,
  Minus,
  Plus,
  Search,
  TriangleAlert,
  X,
  Copy,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  SquareCode,
  Heading1,
  Heading2,
  Heading3,
  List,
  ListOrdered,
  TextQuote,
  Link,
  Undo2,
  Redo2,
  Eye,
} from "lucide-react";
import type { IconSet } from "../types";

/**
 * Ready-made icon set for lucide-react.
 * Usage: <IconProvider icons={lucideIcons}>
 */
export const lucideIcons: IconSet = {
  spinner: LoaderCircle,
  check: Check,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsUpDown: ChevronsUpDown,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  minus: Minus,
  plus: Plus,
  search: Search,
  more: Ellipsis,
  lock: Lock,
  info: Info,
  success: CircleCheck,
  error: CircleAlert,
  warning: TriangleAlert,
  calendar: Calendar,
  panelLeft: PanelLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpDown: ArrowUpDown,
  gripVertical: GripVertical,
  copy: Copy,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  codeBlock: SquareCode,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  list: List,
  listOrdered: ListOrdered,
  quote: TextQuote,
  link: Link,
  undo: Undo2,
  redo: Redo2,
  eye: Eye,
};
